#!/bin/bash

shopt -s expand_aliases

touch .dummy

if sed -i "" -e "" .dummy 2>/dev/null; then
  alias sedi='sed -i "" '
else
  alias sedi='sed -i '
fi

rm .dummy

if [ $# -ne 2 ];
  then echo "Usage: logue_gen [osc/delfx/revfx/modfx] [project_name]"
  exit 1
fi  

TYPE=$1
PROJECT=$2

if [ $TYPE == 'osc' ]; then
  :
elif [ $TYPE == 'delfx' ]; then
  :
elif [ $TYPE == 'revfx' ]; then
  :
elif [ $TYPE == 'modfx' ]; then
  :
else
  echo 'invalid TYPE'
  exit 1
fi

if [ -z $PROJECT ]; then
  echo 'PROJECT is required'
  exit 1
fi


PROJECTDIR=$TYPE/projects/$PROJECT

if [ -e $PROJECTDIR ]; then
  echo Project $PROJECT already exists.
  read -p "Overwite? [y/N]: " yn

  case "$yn" in [yY]*) ;; *) echo "" ; exit ;; esac

  rm -rf $PROJECTDIR
fi  

  

mkdir $PROJECTDIR
cp -a $TYPE/template/* $PROJECTDIR
mv $PROJECTDIR/template.cpp $PROJECTDIR/$PROJECT.cpp
sedi -e "s/\$PROJECT/$PROJECT/g" $PROJECTDIR/manifest.json
sedi -e "s/\$PROJECT/$PROJECT/g" $PROJECTDIR/project.mk

echo "generate: $PROJECTDIR"
